function Map(){
	let mapList=[];
	mapList['?mini']=[
		['block','block','block','block','block','block','block','block','block','block','block','block','block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'air'  ,'block','block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'air'  ,'block','block'],
		['block','trap', 'block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','trap' ,'air'  ,'block','block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'air'  ,'block','air'  ,'air'  ,'block','block'],
		['block','trap' ,'block','air'  ,'air'  ,'air'  ,'air'  ,'trap' ,'block','air'  ,'air'  ,'air'  ,'block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'trap' ,'block','block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'block','air'  ,'air'  ,'block','block'],
		['block','trap' ,'block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','air'  ,'block','block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'block','trap' ,'air'  ,'trap' ,'block'],
		['block','air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'air'  ,'trap' ,'air'  ,'air'  ,'block'],
		['block','air'  ,'air'  ,'block','trap' ,'air'  ,'trap' ,'block','air'  ,'air'  ,'trap' ,'air'  ,'block'],
		['block','air'  ,'trap' ,'trap' ,'air'  ,'trap' ,'air'  ,'trap' ,'trap' ,'trap' ,'trap' ,'block','block'],
		['block','block','block','block','block','block','block','block','block','block','block','block','block'],
	];
	mapList['?debug']=mapList['?mini'];
	mapList['?huge']=[
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'block', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'block', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'trap', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'trap', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'trap', 'block', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'block', 'trap', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'trap', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'trap', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'trap', 'air', 'trap', 'air', 'trap', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'trap', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'trap', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block'],
		['block', 'air', 'air', 'block', 'air', 'block', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block'],
		['block', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block'],
		['block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block'],
		['block', 'block', 'block', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'block', 'air', 'air', 'air', 'air', 'block', 'block', 'block', 'block'],
		['block', 'air', 'block', 'air', 'block', 'air', 'block', 'air', 'block', 'block', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'block', 'block', 'air', 'block'],
		['block', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'air', 'block', 'air', 'air', 'air', 'air', 'block', 'air', 'block', 'air', 'air', 'air', 'block', 'air', 'block'],
		['block', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'trap', 'block'],
		['block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block', 'block'],
	];
	function check(x,y){
		return x>=0&&x<map.length&&y>=0&&y<map[x].length;
	}
	this.destroy=function(x,y){
		if(!check(x,y))return;
		if(map[x][y]=='block'){
			map[x][y]='air';
		}
	}
	this.insert=function(x,y){
		if(!check(x,y))return;
		if(map[x][y]=='air'&&x+1<map.length&&map[x+1][y]!='air'){
			map[x][y]='block';
		}
	}
	this.makeEntityList=function(){
		let ans=new Array;
		ans.push(new Entity('background',0,0,mapList[location.search][0].length,mapList[location.search].length));
		for(let i=0;i<mapList[location.search].length;i++){
			for(let j=0;j<mapList[location.search][i].length;j++){
				if(mapList[location.search][i][j]!='air'){
					ans.push(new Entity(mapList[location.search][i][j],j,i,1,1));
				}
			}
		}
		return ans;
	}
	this.getBlockValue=function(left,top){
		left=Math.floor(left+0.5);
		top=Math.floor(top+0.5);
		if(!check(top,left))return null;
		return map[top][left];
	}
}